#!/usr/bin/env python3
import sys
import os
sys.path.append('/Users/lenar/envs/project/PyProjects/GitSecretScanner')
from git_scaner import scan_directory
path = os.path.dirname(os.path.dirname(os.getcwd()))
result = scan_directory(path)
if result:
    print("Found a secret, commit aborted")
    sys.exit(1)
else:
    sys.exit(0)

